module(load="imfile")

# Nginx error log files
input(type="imfile"
      File="/var/log/nginx/openwebui_error.log"
      Tag="error.openwebui"
      Facility="local7"
      Severity="error"
      readMode="0"
      ruleset="nginxError")

input(type="imfile"
      File="/var/log/nginx/homeassistant_error.log"
      Tag="error.homeassistant"
      Facility="local7"
      Severity="error"
      readMode="0"
      ruleset="nginxError")

input(type="imfile"
      File="/var/log/nginx/grafana_error.log"
      Tag="error.grafana"
      Facility="local7"
      Severity="error"
      readMode="0"
      ruleset="nginxError")

input(type="imfile"
      File="/var/log/nginx/prometheus_error.log"
      Tag="error.prometheus"
      Facility="local7"
      Severity="error"
      readMode="0"
      ruleset="nginxError")

input(type="imfile"
      File="/var/log/nginx/loki_error.log"
      Tag="error.loki"
      Facility="local7"
      Severity="error"
      readMode="0"
      ruleset="nginxError")

input(type="imfile"
      File="/var/log/nginx/solax_error.log"
      Tag="error.solax"
      Facility="local7"
      Severity="error"
      readMode="0"
      ruleset="nginxError")

input(type="imfile"
      File="/var/log/nginx/telegraf_error.log"
      Tag="error.telegraf"
      Facility="local7"
      Severity="error"
      readMode="0"
      ruleset="nginxError")

template(name="nginxErrorTemplate" type="string"
  string="<%PRI%>1 %TIMESTAMP:::date-rfc3339% %HOSTNAME% %APP-NAME% %PROCID% - - %msg%\n")

ruleset(name="nginxError") {
    action(type="omfwd"
           target="127.0.0.1"
           port="514"
           protocol="tcp"
           template="nginxErrorTemplate")
}
