module(load="imfile")

input(type="imfile"
      File="/var/log/nginx/openwebui_access.json"
      Tag="nginx.access.openwebui"
      Facility="local7"
      Severity="info"
      readMode="0"
      ruleset="nginxAccess"
)

input(type="imfile"
      File="/var/log/nginx/homeassistant_access.json"
      Tag="nginx.access.homeassistant"
      Facility="local7"
      Severity="info"
      readMode="0"
      ruleset="nginxAccess"
)

input(type="imfile"
      File="/var/log/nginx/grafana_access.json"
      Tag="nginx.access.grafana"
      Facility="local7"
      Severity="info"
      readMode="0"
      ruleset="nginxAccess"
)

input(type="imfile"
      File="/var/log/nginx/prometheus_access.json"
      Tag="nginx.access.prometheus"
      Facility="local7"
      Severity="info"
      readMode="0"
      ruleset="nginxAccess"
)

input(type="imfile"
      File="/var/log/nginx/loki_access.json"
      Tag="nginx.access.loki"
      Facility="local7"
      Severity="info"
      readMode="0"
      ruleset="nginxAccess"
)

input(type="imfile"
      File="/var/log/nginx/solax_access.json"
      Tag="nginx.access.solax"
      Facility="local7"
      Severity="info"
      readMode="0"
      ruleset="nginxAccess"
)

input(type="imfile"
      File="/var/log/nginx/telegraf_access.json"
      Tag="nginx.access.telegraf"
      Facility="local7"
      Severity="info"
      readMode="0"
      ruleset="nginxAccess"
)

template(name="rfc5424_nginx" type="string"
  string="<%PRI%>1 %TIMESTAMP:::date-rfc3339% %HOSTNAME% %APP-NAME% %PROCID% - - %msg%\n"
)

ruleset(name="nginxAccess") {
    action(type="omfwd"
           target="127.0.0.1"
           port="514"
           protocol="tcp"
           template="rfc5424_nginx")
}
