services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "${PUID}:${PGID}"
    ports:
      - ${GRAFANA_PORT:-3000}:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - type: bind
        source: ${DATA_DIR}/grafana/var/lib/grafana
        target: /var/lib/grafana
      - type: bind
        source: ${BASE_DIR}/grafana/etc/grafana
        target: /etc/grafana
    restart: unless-stopped

  blackbox-exporter:
    image: quay.io/prometheus/blackbox-exporter:latest
    container_name: blackbox-exporter
    command:
      - '--config.file=/config/blackbox.yml'
    user: "${PUID}:${PGID}"
    cap_add:
      - NET_RAW #required to do ICMP probing
    ports:
      - ${BLACKBOX_EXPORTER_PORT:-9115}:9115
    volumes:
      - type: bind
        source: ${BASE_DIR}/blackbox-exporter/config
        target: /config
    restart: unless-stopped


  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    user: "${PUID}:${PGID}"
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - ${ALERTMANAGER_PORT:-9093}:9093
    volumes:
      - type: bind
        source: ${BASE_DIR}/alertmanager/config
        target: /etc/alertmanager
      - type: bind
        source: ${DATA_DIR}/alertmanager
        target: /alertmanager
    restart: unless-stopped

  fluent-bit:
    image: cr.fluentbit.io/fluent/fluent-bit:5.0
    container_name: fluent-bit
    user: "${PUID}:${PGID}"
    environment:
      - TZ=Europe/Amsterdam
    command:
      - '-c'
      - '/etc/fluent-bit/fluent-bit.yaml'
    ports:
      - ${FLUENT_BIT_PORT:-514}:5140
    volumes:
      - type: bind
        source: ${BASE_DIR}/fluent-bit/etc/fluent-bit
        target: /etc/fluent-bit
      - type: bind
        source: ${DATA_DIR}/fluent-bit
        target: /var/log/fluent-bit
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    user: "${PUID}:${PGID}"
    command:
      - '-config.file=/etc/loki/loki-config.yaml'
    ports:
      - ${LOKI_PORT:-3100}:3100
    volumes:
      - type: bind
        source: ${BASE_DIR}/loki/etc/loki
        target: /etc/loki
      - type: bind
        source: ${DATA_DIR}/loki/chunks
        target: /etc/loki/chunks
      - type: bind
        source: ${DATA_DIR}/loki/rules
        target: /etc/loki/rules
    restart: unless-stopped


networks:
  default:
    name: monitoring_network
    external: true
