services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: "${PUID}:${PGID}"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      #- --storage.tsdb.retention.time 2y
      - '--storage.tsdb.retention.size=256GB'
      - '--web.enable-admin-api'
    ports:
      - ${PROMETHEUS_PORT:-9090}:9090
    volumes:
      - type: bind
        source: ${BASE_DIR}/prometheus/etc/prometheus
        target: /etc/prometheus
      - type: bind
        source: ${DATA_DIR}/prometheus
        target: /prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "${PUID}:${PGID}"
    ports:
      - ${GRAFANA_PORT:-3000}:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - type: bind
        source: ${DATA_DIR}/grafana/var/lib/grafana
        target: /var/lib/grafana
      - type: bind
        source: ${BASE_DIR}/grafana/etc/grafana
        target: /etc/grafana
    restart: unless-stopped

  blackbox-exporter:
    image: quay.io/prometheus/blackbox-exporter:latest
    container_name: blackbox-exporter
    command:
      - '--config.file=/config/blackbox.yml'
    user: "${PUID}:${PGID}"
    cap_add:
      - NET_RAW #required to do ICMP probing
    ports:
      - ${BLACKBOX_EXPORTER_PORT:-9115}:9115
    volumes:
      - type: bind
        source: ${BASE_DIR}/blackbox-exporter/config
        target: /config
    restart: unless-stopped


  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    user: "${PUID}:${PGID}"
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - ${ALERTMANAGER_PORT:-9093}:9093
    volumes:
      - type: bind
        source: ${BASE_DIR}/alertmanager/config
        target: /etc/alertmanager
      - type: bind
        source: ${DATA_DIR}/alertmanager
        target: /alertmanager
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:2.1.3
    container_name: uptime-kuma
    ports:
      - ${UPTIME_KUMA_PORT:-3001}:3001
    volumes:
      - type: bind
        source: ${BASE_DIR}/uptimekuma/data
        target: /app/data
    environment:
      - TZ=UTC  # Set the timezone (change to your preferred local timezone so monitoring times are the same)
      - UMASK=0022  # Set your file permissions manually
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    dns:
      - ${DNS_SERVERS}

networks:
  default:
    name: monitoring_network
