alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: "hass"
    scrape_interval: 60s
    metrics_path: /api/prometheus
    scheme: http
    static_configs:
      - targets: ['homeassistant.home:8123']
  
  - job_name: "cloud"
    scrape_interval: 60s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['telegraf.cloud.home:9292']

  - job_name: 'ai'
    scrape_interval: 30s
    static_configs:
      - targets: ['ai.home:9100']
  
  - job_name: 'ai-amd_gpu'
    scrape_interval: 30s
    static_configs:
      - targets: ['ai.home:5000']

  - job_name: 'ai-llama'
    scrape_interval: 30s
    static_configs:
      - targets:
        - model.cloud.home?model=Baloza-v0.3
        - model.cloud.home?model=ninni-v0.1
    metrics_path: /metrics
    relabel_configs:
      # Strip query parameters, keep only hostname
      - source_labels: [__address__]
        regex: '([^?]+)'
        target_label: __param_target
        replacement: '$1'
      # Extract model parameter as a label
      - source_labels: [__address__]
        regex: '.*model=([^&]+).*'
        target_label: model

  - job_name: blackbox-probes
    scrape_interval: 30s
    metrics_path: /probe
    static_configs:
      - targets:
        - http://homeassistant.home:8123
        - http://darwish.cloud.home/health
        - http://music.home/api/v1/ping
        labels:
          module: http_2xx
      - targets:
        - 192.168.50.1
        labels:
          module: icmp
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        regex: '^(?:https?://)?([a-zA-Z][a-zA-Z0-9-]*)\..*|^(.+)$'
        target_label: instance
        replacement: '$1$2'
      - source_labels: [module]
        target_label: __param_module
      - target_label: __address__
        replacement: blackbox-exporter:9115
