server {
	listen 8181 default_server;
	listen [::]:8181 default_server;

  # Logging
  access_log /var/log/nginx/solax_access.log;
  error_log /var/log/nginx/solax_error.log;

	location / {
		proxy_pass http://5.8.8.8:80;
	}
}
