upstream telegraf {
	server localhost:9273;
}

server {
	listen 9292;
	listen [::]:9292;
	server_name telegraf.cloud.home;

	access_log /var/log/nginx/telegraf_access.json json_combined;
  error_log /var/log/nginx/telegraf_error.log;
	root /usr/share/nginx/www;
	index index.html index.htm;

	location / {
		proxy_set_header Host $host;
		proxy_pass http://telegraf;
	}
}
